# Generated by Django 5.0.6 on 2024-06-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(blank=True, null=True, verbose_name='Fecha de la entrevista')),
                ('interviewer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del entrevistador')),
                ('reason_for_interview', models.TextField(blank=True, null=True, verbose_name='Razón de la entrevista')),
                ('background_info', models.TextField(blank=True, null=True, verbose_name='Información de antecedentes')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Entrevista Inicial',
                'verbose_name_plural': 'Entrevistas Iniciales',
            },
        ),
    ]
