# Generated by Django 5.0.6 on 2024-06-17 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        ('interview', '0002_initialinterview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialinterview',
            name='user',
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='academy.student'),
        ),
    ]
