# Generated by Django 5.0.6 on 2024-06-18 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_alter_subject_options'),
        ('group', '0002_group_subjects_alter_group_career_alter_group_group_and_more'),
        ('interview', '0003_remove_initialinterview_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialinterview',
            options={},
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='actividad_hermanos',
            field=models.TextField(blank=True, null=True, verbose_name='Actividad de los hermanos'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='ayuda_psicologica',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Recibes ayuda psicológica?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='beca_bachillerato',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tuviste beca en el bachillerato? si la respuesta es SI marca la casilla'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='cantidad_libros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad de libros de apoyo'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.career', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='carrera_primera_opcion',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Es esta carrera tu primera opción?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='computadora_internet',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tienes computadora con internet?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='con_quien_vives',
            field=models.CharField(blank=True, choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Ambos', 'Ambos'), ('Otros', 'Otros')], max_length=20, null=True, verbose_name='¿Con quién vives?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='cual_espacio_estudio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuál es tu espacio de estudio?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='cual_otra_escuela',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿En qué otra escuela estudiaste?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='cual_tecnica_estudio',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuál técnica de estudio?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='cuales_materias_reprobadas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuáles materias reprobaste?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='cualidades',
            field=models.TextField(blank=True, null=True, verbose_name='Cualidades'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='cuatrimestre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuatrimestre'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='debilidades',
            field=models.TextField(blank=True, null=True, verbose_name='Debilidades'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='dependes_economicamente',
            field=models.CharField(blank=True, choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Tú', 'Tú'), ('Ambos', 'Ambos'), ('Otros', 'Otros')], max_length=20, null=True, verbose_name='¿De quién dependes económicamente?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='dependientes_economicos',
            field=models.TextField(blank=True, null=True, verbose_name='Dependientes económicos'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='discapacidad',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tienes alguna discapacidad?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='disgustos',
            field=models.TextField(blank=True, null=True, verbose_name='Disgustos'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='escuela_procedencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Escuela de procedencia'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='espacio_estudio',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tienes un espacio adecuado para estudiar?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='especialidad_promedio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad y promedio'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Otro', 'Otro')], max_length=10, null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='estado_civil_otro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro (estado civil)'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='estado_salud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de salud'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='examen_admision',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Realizaste el examen de admisión?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='expectativas_carrera',
            field=models.TextField(blank=True, null=True, verbose_name='Expectativas de la carrera'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='forma_trabajar',
            field=models.CharField(blank=True, choices=[('Solo', 'Solo'), ('En equipo', 'En equipo'), ('Binas', 'Binas'), ('Grupal', 'Grupal')], max_length=10, null=True, verbose_name='Forma de trabajar'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='futuro_academico',
            field=models.TextField(blank=True, null=True, verbose_name='Futuro académico'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='futuro_personal',
            field=models.TextField(blank=True, null=True, verbose_name='Futuro personal'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='futuro_profesional',
            field=models.TextField(blank=True, null=True, verbose_name='Futuro profesional'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='grupo_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Grupo escolar'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='habilidades',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidades'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='hermanos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de hermanos'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='horario_laboral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario laboral'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='horas_trabajo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas de trabajo'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='ingreso_madre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso de la madre'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='ingreso_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso mensual'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='ingreso_padre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso del padre'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='libros_apoyo',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Usas libros de apoyo?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='lugar_entre_hermanos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar entre hermanos'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='lugar_procedencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de procedencia'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='materias_dificultad',
            field=models.TextField(blank=True, null=True, verbose_name='Materias con dificultad'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='materias_facil',
            field=models.TextField(blank=True, null=True, verbose_name='Materias fáciles'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='materias_reprobadas',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Reprobaste materias?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='motivacion_estudio',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Tienes motivación para estudiar?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='motivo_ayuda',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de la ayuda psicológica'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='motivo_beca',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de la beca'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='motivo_carrera_opcion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo para elegir esta opción de carrera'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='motivo_forma_trabajar',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo para la forma de trabajar'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='motivo_motivacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de la motivación'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='motivo_universidad',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo para elegir esta universidad'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='motivo_universidad_opcion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo para elegir esta opción de universidad'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='nombre_tutor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del tutor'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='ocupacion_madre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación de la madre'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='ocupacion_padre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación del padre'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='otros_dependientes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Otros dependientes'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='otros_familiares',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Otros familiares'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='pareja_sentimental',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pareja sentimental'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='planes_matrimonio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Planes de matrimonio'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='planes_terminar_carrera',
            field=models.TextField(blank=True, null=True, verbose_name='Planes para terminar la carrera'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='problemas_personales',
            field=models.TextField(blank=True, null=True, verbose_name='Problemas personales'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='requieres_beca',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Requieres beca? si la respuesta es SI marca la casilla'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tecnica_estudio',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Usas alguna técnica de estudio?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='temores',
            field=models.TextField(blank=True, null=True, verbose_name='Temores'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tiempo_libre',
            field=models.TextField(blank=True, null=True, verbose_name='Tiempo libre'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tipo_beca_bachillerato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de beca en bachillerato'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tipo_casa',
            field=models.CharField(blank=True, choices=[('Propia', 'Propia'), ('Rentada', 'Rentada'), ('Prestada', 'Prestada'), ('Otros', 'Otros')], max_length=10, null=True, verbose_name='Tipo de casa'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tipo_casa_otros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otros (tipo de casa)'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tipo_computadora',
            field=models.CharField(blank=True, choices=[('PC', 'PC'), ('Laptop', 'Laptop')], max_length=10, null=True, verbose_name='Tipo de computadora'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tipo_discapacidad',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de discapacidad'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tipo_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de empresa'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tipo_internet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de conexión a internet'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tipo_religion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de religión'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tipo_trabajo',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de trabajo que te gustaría tener'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tipo_tratamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de tratamiento médico'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='trabajas',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Trabajas? si la respuesta es SI marca la casilla en caso contrario omite las siguientes preguntas'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='transporte_universidad',
            field=models.TextField(blank=True, null=True, verbose_name='Transporte a la universidad'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='tratamiento_medico',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Estás en tratamiento médico?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='universidad_primera_opcion',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Es esta universidad tu primera opción?'),
        ),
        migrations.AddField(
            model_name='initialinterview',
            name='valores',
            field=models.TextField(blank=True, null=True, verbose_name='Valores'),
        ),
    ]
