# Generated by Django 5.0.6 on 2024-06-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_initialinterview_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialinterview',
            name='interviewer_name',
        ),
    ]
