# Generated by Django 5.0.6 on 2024-06-18 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_remove_initialinterview_interviewer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialinterview',
            name='background_info',
        ),
        migrations.RemoveField(
            model_name='initialinterview',
            name='cuatrimestre',
        ),
        migrations.RemoveField(
            model_name='initialinterview',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='initialinterview',
            name='reason_for_interview',
        ),
    ]
