# Generated by Django 5.0.6 on 2024-06-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_remove_initialinterview_background_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialinterview',
            options={'verbose_name': 'Entrevista Inicial', 'verbose_name_plural': 'Entrevistas Iniciales'},
        ),
    ]
