# Generated by Django 5.0.6 on 2024-06-21 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_subjects_alter_group_career_alter_group_group_and_more'),
        ('interview', '0007_alter_initialinterview_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialinterview',
            name='grupo_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='group.group', verbose_name='Grupo escolar'),
        ),
    ]
