# Generated by Django 5.0.6 on 2024-07-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_alter_initialinterview_grupo_escolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialinterview',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
