# Generated by Django 5.0.6 on 2024-05-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['year'], 'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
    ]
