# Generated by Django 5.0.6 on 2024-06-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0003_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(max_length=2, verbose_name='Cuatrimestre'),
        ),
    ]
