# Generated by Django 5.0.6 on 2024-05-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100, verbose_name='Concepto')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('hours', models.IntegerField(default=0, verbose_name='Horas')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
    ]
