# Generated by Django 5.0.6 on 2024-05-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_load', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concepts',
            new_name='Concept',
        ),
    ]
