# Generated by Django 5.0.6 on 2024-05-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_load', '0002_rename_concepts_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
