# Generated by Django 5.0.6 on 2024-06-04 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('period', '0004_alter_semester_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='fmonth_period',
        ),
        migrations.AddField(
            model_name='group',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='period.semester'),
        ),
    ]
