# Generated by Django 5.0.6 on 2024-06-20 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Justificante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=255)),
                ('tsu', models.BooleanField(default=False)),
                ('ingenieria', models.BooleanField(default=False)),
                ('dias_falta', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=255)),
                ('adjuntar_archivos', models.FileField(blank=True, null=True, upload_to='justificantes/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.CharField(default='2024', max_length=4)),
                ('profesores', models.ManyToManyField(related_name='profesores_justificantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
