<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-07-11 20:45
=======
# Generated by Django 5.0.6 on 2024-07-02 22:12
>>>>>>> 6f090a2eb5e85cc6abc08eb5dc1336debb891f26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
<<<<<<< HEAD
            field=models.EmailField(default='default@example.com', max_length=254),
=======
            field=models.EmailField(default='mail@mail.com', max_length=254),
>>>>>>> 6f090a2eb5e85cc6abc08eb5dc1336debb891f26
            preserve_default=False,
        ),
    ]
