# Generated by Django 5.0.6 on 2024-06-11 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('TSU', 'Técnico Superior Universitario'), ('Ing', 'Ingeniería'), ('Lic', 'Licenciatura'), ('M', 'Maestría')], max_length=10, verbose_name='Nivel')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=20, verbose_name='Abreviatura')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('year_plan', models.CharField(blank=True, max_length=4, null=True, verbose_name='Plan de estudios')),
            ],
            options={
                'verbose_name': 'carrera',
                'verbose_name_plural': 'carreras',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('teorical_hours', models.IntegerField(verbose_name='Horas teóricas')),
                ('practical_hours', models.IntegerField(verbose_name='Horas prácticas')),
                ('total_hours', models.IntegerField(verbose_name='Horas totales')),
                ('file', models.CharField(blank=True, max_length=200, null=True, verbose_name='Archivo')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.semester')),
            ],
            options={
                'verbose_name': 'materia',
                'verbose_name_plural': 'materias',
            },
        ),
    ]
