# Generated by Django 5.0.6 on 2024-06-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_subject_career_alter_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semanal_hours',
            field=models.IntegerField(default=0, verbose_name='Horas semanales'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practical_hours',
            field=models.IntegerField(default=0, verbose_name='Horas prácticas'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teorical_hours',
            field=models.IntegerField(default=0, verbose_name='Horas teóricas'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_hours',
            field=models.IntegerField(default=0, verbose_name='Horas totales'),
        ),
    ]
