# Generated by Django 5.0.6 on 2024-06-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_subject_semanal_hours_alter_subject_practical_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['career', 'semester'], 'verbose_name': 'materia', 'verbose_name_plural': 'materias'},
        ),
    ]
