# Generated by Django 5.0.6 on 2024-08-16 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0006_professor_category'),
        ('career', '0004_alter_subject_options'),
        ('group', '0002_group_subjects_alter_group_career_alter_group_group_and_more'),
        ('period', '0002_alter_period_options_alter_semester_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalizacionAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('evidencia_canalizacion_alumno', models.FileField(upload_to='evidencias/pdf_canalizacion', verbose_name='Evidencia pdf_canalizacion')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career', verbose_name='Carrera')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Grupo')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.semester', verbose_name='Semestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.student', verbose_name='Estudiante')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.professor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Canalización del Alumno',
                'verbose_name_plural': 'Canalizaciones de Alumnos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteTutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tutoria', models.DateField(verbose_name='Fecha de Tutoría')),
                ('nombre_actividad', models.CharField(max_length=255, verbose_name='Nombre de la Actividad')),
                ('objetivo_actividad', models.TextField(verbose_name='Objetivo de la Actividad')),
                ('descripcion_actividad', models.TextField(verbose_name='Descripción de la Actividad')),
                ('evidencia_fotografica', models.FileField(upload_to='evidencias/imagenes_videos', verbose_name='Evidencia fotografica')),
                ('evidencia_lista_asistencia', models.FileField(upload_to='evidencias/pdf', verbose_name='Evidencia list_asistencia')),
                ('evidencia_audio', models.FileField(upload_to='evidencias/audio', verbose_name='Evidencia de audio')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career', verbose_name='Carrera')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Grupo')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.semester', verbose_name='Semestre')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.professor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Reporte de Tutoría',
                'verbose_name_plural': 'Reportes de Tutorías',
                'ordering': ['-fecha_tutoria'],
            },
        ),
    ]
