# Generated by Django 5.0.6 on 2024-07-19 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0006_professor_category'),
        ('career', '0004_alter_subject_options'),
        ('group', '0002_group_subjects_alter_group_career_alter_group_group_and_more'),
        ('period', '0002_alter_period_options_alter_semester_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteTutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tutoria', models.DateField(verbose_name='Fecha de Tutoría')),
                ('nombre_actividad', models.CharField(max_length=255, verbose_name='Nombre de la Actividad')),
                ('objetivo_actividad', models.TextField(verbose_name='Objetivo de la Actividad')),
                ('descripcion_actividad', models.TextField(verbose_name='Descripción de la Actividad')),
                ('evidencia1', models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia 1')),
                ('evidencia2', models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia 2')),
                ('evidencia3', models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia 3')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career', verbose_name='Carrera')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Grupo')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.semester', verbose_name='Semestre')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.professor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Reporte de Tutoría',
                'verbose_name_plural': 'Reportes de Tutorías',
                'ordering': ['-fecha_tutoria'],
            },
        ),
    ]
