# Generated by Django 5.0.6 on 2024-07-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_tutoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportetutoria',
            name='evidencia1',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia fotografica'),
        ),
        migrations.AlterField(
            model_name='reportetutoria',
            name='evidencia2',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia list_asistencia'),
        ),
        migrations.AlterField(
            model_name='reportetutoria',
            name='evidencia3',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia pdf_canalizacion'),
        ),
    ]
