# Generated by Django 5.0.6 on 2024-07-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_delete_guest_delete_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
