# Generated by Django 5.0.6 on 2024-06-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Celular'),
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero_seguro_social',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de seguro social'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de emergencia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo de sangre'),
        ),
    ]
