# Generated by Django 5.0.6 on 2024-06-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_customuser_is_professor_customuser_is_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
