# Generated by Django 5.0.6 on 2024-07-11 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_admin'),
        ('testvak', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heinterview',
            name='B5',
        ),
        migrations.RemoveField(
            model_name='heinterview',
            name='C1',
        ),
        migrations.RemoveField(
            model_name='heinterview',
            name='E3',
        ),
        migrations.RemoveField(
            model_name='heinterview',
            name='E4',
        ),
        migrations.RemoveField(
            model_name='heinterview',
            name='F2',
        ),
        migrations.AddField(
            model_name='heinterview',
            name='HE23',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Atiendes al profesor, tratando de entender todo lo que dice?'),
        ),
        migrations.AddField(
            model_name='heinterview',
            name='HE35',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Revisas y completas tus apuntes con otro compañero?'),
        ),
        migrations.AddField(
            model_name='heinterview',
            name='HE47',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Escribes los datos importantes que te son difíciles para recordar?'),
        ),
        migrations.AddField(
            model_name='heinterview',
            name='HE52',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Entregas a tiempo tus tareas, trabajos, etcétera?'),
        ),
        migrations.AddField(
            model_name='heinterview',
            name='HE72',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Tratas de entregar lo máximo de ti para obtener un buen resultado escolar?'),
        ),
        migrations.AddField(
            model_name='heinterview',
            name='HE73',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Utilizas alguna técnica de relajación para reducir la ansiedad antes o durante los exámenes?'),
        ),
        migrations.AddField(
            model_name='heinterview',
            name='HE74',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Estás satisfecho con tus resultados escolares?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE1',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Trabajas siempre en el mismo lugar?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE10',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Tu silla es proporcionada en altura a la mesa de trabajo?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE11',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Cuentas con una agenda o calendario para administrar tu tiempo?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE12',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Tienes un horario fijo para estudiar y descansar?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE13',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Has realizado una planificación anotando el tiempo que debes de dedicar a tu estudio diariamente?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE14',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Tu planificación ¿Incluye el tiempo estimado que emplearas en el estudio de todas las asignaturas?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE15',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Incluyes períodos de descanso en tu plan de estudio?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE16',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Estudias al menos 5 días por semana?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE17',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Antes de comenzar y antes de estudiar ¿Determinas tu plan de trabajo y el tiempo que vas a tardar en demorar en realizarlo?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE18',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Realizas primero los trabajos más difíciles que los fáciles?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE19',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Acudes diariamente a todas las clases?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE2',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿El lugar que tienes para estudiar esta aislado de ruido?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE20',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Miras con interés al profesor cuando explica?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE21',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Anotas las tareas que debes de realizar en tu casa?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE22',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Realizas las tareas que te asignan tus docentes?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE24',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Preguntas cuando hay algo que no entiendes?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE25',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Tu profesor te motiva a estudiar o repasar lo visto en clase?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE26',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Tu profesor te motiva a investigar más de los temas vistos en clases?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE27',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Prefieres trabajar solo cuando tienes que realizar alguna actividad en clase o fuera de la escuela?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE28',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Participas en actividades de grupo en el salón de clase?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE29',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Tomas apuntes de lo que los profesores explican?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE3',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Te cuesta trabajo concentarte para estudiar?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE30',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Antes de tomar apuntes ¿Escribes la fecha y el título del tema?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE31',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Escribes en todas las asignaturas?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE32',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Tu profesor te motiva?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE33',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Utilizas lápiz de color para destacar lo más importante?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE34',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Anotas las palabras extrañas y lo que no comprendes?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE36',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Acostumbras a mirar el índice de un texto antes de empezar a estudiar?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE37',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Realizar una lectura rápida del texto, previo al estudio más detallado?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE38',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Te apoyas de los apuntes tomados en clase para estudiar una asignatura?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE39',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Identificas las ideas principales de los textos?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE4',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿El lugar donde estudias tiene buena iluminacion(Luz natural o artificial a la hora de estudiar)?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE40',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Subrayas las ideas principales de los textos?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE41',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Cuándo tienes distintas fuentes de información para un mismo tema ¿Haces un resumen para terminar con una síntesis general?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE42',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Utilizas en tu estudio habitual técnicas como el esquema, cuadros, gráficos etcétera?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE43',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Acostumbras a memorizar las ideas principales de un tema?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE44',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Utilizas las fichas de estudio para memorizar alguna fecha, número, datos concretos o vocabulario?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE45',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Utilizas el diccionario para aclarar tus ideas con respecto a una palabra, tanto para su significado como para su ortografía?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE46',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Marcas lo que no comprendes?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE48',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Utilizas alguna técnica para memorizar estos datos?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE49',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Repasas las materias?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE5',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Tiene tu habitacion limpieza, orden y buena iluminacion?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE50',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Pides ayuda a tus profesores, compañeros o padres, cuando tienes dificultades en tus estudios?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE51',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Mantienes tus cuadernos y tareas al día?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE53',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Cumples con la planificación de estudio que te has propuesto para una sesión de trabajo?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE54',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Haces esquemas de las asignaturas que no comprendes los temas vistos en clases?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE55',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Al realizar los esquemas ¿Consideras tus propios apuntes?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE56',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Utilizas los esquemas para facilitar la comprensión de los temas más fáciles?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE57',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Destacas las ideas principales al hacer tus esquemas?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE58',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Respetas la “sangría” para comenzar un párrafo?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE59',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Consultas otros libros además de tu texto de estudio?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE6',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿La temperatura del lugar donde estudias se encuentra entre los 20° a 22° grados?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE60',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Redactas tus trabajos en forma clara, coherente y concisa?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE61',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Revisas la ortografía, redacción, y limpieza en tus trabajos?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE62',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Te gusta estudiar?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE63',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Tienes clara las razones por las que estudias?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE64',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿El estudio es para ti un medio para aprender?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE65',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Te gusta lo que aprendes con tus docentes?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE66',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Logras una buena concentración desde el comienzo de tu sesión de estudio?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE67',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Cuando faltas a clase ¿Procuras informarte de lo que se ha realizado y de lo que se va a realizar?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE68',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Piensas que las personas deben estudiar para aprender y no sólo para aprobar una asignatura?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE69',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Estudias antes de presentar un examen?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE7',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Te gusta estudiar con la ventana abierta o entreabierta?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE70',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Presentas tu examen solo con los conocimientos que posees?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE71',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Cuándo te has sacado una mala nota, intentas superar tu estado de ánimo continuando con interés en las materias?'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE8',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Cuándo empiezas a estudiar, tienes a mano todo el material necesario? (Libros, diccionario, etcétera).'),
        ),
        migrations.AlterField(
            model_name='heinterview',
            name='HE9',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10, null=True, verbose_name='¿Estudias en una silla de respaldo que permita sentarte apoyando bien tu espalda, sin posturas defectuosas?'),
        ),
        migrations.CreateModel(
            name='VAKResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_A', models.IntegerField(default=0)),
                ('count_B', models.IntegerField(default=0)),
                ('count_C', models.IntegerField(default=0)),
                ('count_D', models.IntegerField(default=0)),
                ('count_E', models.IntegerField(default=0)),
                ('count_F', models.IntegerField(default=0)),
                ('count_G', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vak_results', to='academy.student')),
            ],
            options={
                'verbose_name': 'Resultados de VAK',
                'verbose_name_plural': 'Resultados de VAK',
            },
        ),
    ]
