# Generated by Django 5.0.6 on 2024-07-11 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0002_alter_exam_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='period',
            new_name='stage',
        ),
    ]
