# Generated by Django 5.0.6 on 2024-07-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocational', '0003_rename_period_exam_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='career',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='stage',
        ),
    ]
